### ISSUE TITLE
Add default transaction options in truffle console

### ISSUE THREAD

**Issue by ivanzhelyazkov** [ConsenSys-archive/truffle#1451]
**This is only a suggestion for improvements of your interface.**
When you enter truffle console on a test or main network, it would be a huge time-saver to be able to specify the gasPrice of transactions automatically, due to differing transaction times and some transactions not passing at all.

For example : 
By typing _contract.sendTransaction(10000)_,
the truffle console automatically appends _{gasPrice : 1100000000000}_ to the argument list,
so as to make _contract.sendTransaction(10000, {gasPrice: 1100000000000})_.

This will make the interface a lot friendlier and quicker to use by ethereum developers.

**Comment by eggplantzzz** [comment]
@LittleHack Sorry for the delay in getting to you! Thanks for the suggestion, I think we've already implemented the kind of thing you are suggesting! Check out the network options in the docs for configuring Truffle here https://truffleframework.com/docs/truffle/reference/configuration#networks
