### ISSUE TITLE
improve error handling when using `truffle` and you make a typo in the command part

### ISSUE THREAD

**Issue by pedro-nonfree** [ConsenSys-archive/truffle#5828]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

When try to run `truffle test` and I do something like `truffle tes` or any typo you can think of, I get a very strange error, and I am not thinking that the problem is in my typo in the CLI command but in the tests or in my code.

It happened two times on me, on first time, I was debugging my tests for 30 minutes, and it magically started to work after having a break. On second time I found this problem so that's why I am filling this issue as a Developer eX``perience bug 

## Steps to Reproduce

```
[14:33:02] $ truffle tes
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./contracts/LoraCoin.sollc-bin. Attempt #1
> Compiling ./test/test_loracoin.sol
> Artifacts written to /tmp/test--132834-2rdUbv0KLOxE
> Compiled successfully using:
   - solc: 0.8.17+commit.8df45f5f.Emscripten.clang
TypeError: Cannot assign to read only property 'undefined' of object '#<Object>'
    at Object.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/packages/test/dist/src/Test.js:282:1)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/test/dist/src/Test.js:31:1
    at new Promise (<anonymous>)
    at exports.modules.583725.__awaiter (/usr/lib/node_modules/truffle/build/webpack:/packages/test/dist/src/Test.js:27:1)
    at Object.setJSTestGlobals (/usr/lib/node_modules/truffle/build/webpack:/packages/test/dist/src/Test.js:253:1)
    at Object.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/packages/test/dist/src/Test.js:149:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/truffle/build/webpack:/packages/test/dist/src/Test.js:28:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Truffle v5.6.5 (core: 5.6.5)
Node v18.12.1
```

## Expected Behavior

What you expected to happen.

```
truffle tes command not found, run truffle --help to see the available commands for truffle
```

## Actual Results

*See issue and steps to reproduce, or let me know if you need that I reestructure the issue*

## Environment

* Operating System: Debian GNU/Linux 11 (bullseye)
* Ethereum client: Web3.js v1.7.4, ethers 5.7.2
* Truffle version (`truffle version`): Truffle v5.6.5 (core: 5.6.5) Ganache v7.5.0 Solidity v0.5.16 (solc-js) Node v18.12.1 Web3.js v1.7.4
* node version (`node --version`): v18.12.1
* npm version (`npm --version`): 8.19.2

**Comment by eggplantzzz** [comment]
Ah well that is a strange one! Truffle does have some internals that attempt to interpret typo'ed commands so it is expected that it would run the test command. I'll track down what the error is and hopefully get a bug fix in soon. Thank you for reporting this!
