### ISSUE TITLE
when I deploy a smart contract using truffle, it said "Receiving contract could not be identified." what should i do??

### ISSUE THREAD

**Issue by arunk-dev-hub** [ConsenSys-archive/truffle#5915]
![Screenshot 2023-02-21 165627](https://user-images.githubusercontent.com/111792111/220333416-b5a5d37b-a7d3-4649-affb-ba8c1e40bd26.jpg)

**Comment by cliffoo** [comment]
Hey @arunkotla thanks for opening this. Can you try `truffle compile --all` in a separate terminal, in your Truffle project, while dashboard is running?

fyi the screenshot you have there isn't a contract deployment.

**Comment by arunkotla** [comment]
thank   you


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/24/23,
12:50:40 AM
