### ISSUE TITLE
new BigNumber() not a number when deploying OpenZeppelin Crowdsale

### ISSUE THREAD

**Issue by reasv** [ConsenSys-archive/truffle#841]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
I am getting this when deploying the OpenZeppelin Crowdsale, and I don't really understand where the issue is.
```
BigNumber Error: new BigNumber() not a number: function TruffleContract() { 
    this.constructor = temp;
    return Contract.apply(this, arguments);
}
```
The OpenZeppelin contract should be correct since I didn't change it, I just inherited from it.

## Steps to Reproduce
I deploy by running migrate from within truffle develop.
My deployment script is very barebones:
```Javascript
var EToken = artifacts.require("EToken");
var TestIco = artifacts.require("TestIco");

module.exports = function(deployer, network, accounts) {
  deployer.deploy(EToken).then( function (){
    deployer.deploy(TestIco, EToken)
  });

};
```
As are the two smart contracts:
`TestIco.sol`
```Solidity
pragma solidity ^0.4.13;

import 'zeppelin-solidity/contracts/crowdsale/Crowdsale.sol';


contract TestIco is Crowdsale {

  function TestIco(ERC20 _token) Crowdsale(100, msg.sender, _token) {     
  }
}

```
`EToken.sol`
```Solidity
pragma solidity ^0.4.13;

import 'zeppelin-solidity/contracts/token/ERC20/MintableToken.sol';

contract EToken is MintableToken {
  string public name = "Test Token";
  string public symbol = "TTK";
  uint8 public decimals = 18;
}
```

## Full Output
```
Using network 'develop'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x4395ab278561f8d45ebdeeef4a8a8844ed695db2bd53fb3f2010ba3476170f9f
  Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving successful migration to network...
  ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying EToken...
  ... 0x10f312d5f409e3e118532f2aa4d7120115683bdb3846223c215947961c4965e6
  EToken: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
Saving successful migration to network...
  Deploying TestIco...
  ... 0xf36163615f41ef7ed8f4a8f192149a0bf633fe1a2398ce001bf44c43dc7bdda0
(node:18228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): BigNumber Error: new BigNumber() not a number: function TruffleContract() {
        this.constructor = temp;
        return Contract.apply(this, arguments);
      }
(node:18228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Saving artifacts...
```
## Environment

* Operating System: Debian Stretch
* Ethereum client: n/a
* Truffle version (`truffle version`): Truffle v4.1.3 (core: 4.1.3) Solidity v0.4.19 (solc-js)
* node version (`node --version`): v8.9.4
* npm version (`npm --version`): 5.7.1

**Comment by cgewecke** [comment]
@reasv It looks like there might be an issue with the way the `migrations.js` is written - [this](http://truffleframework.com/docs/getting_started/migrations#deployer) is a good first reference for how to deploy interdependent contracts. The pattern suggested there is:
```javascript
// Deploy A, then deploy B, passing in A's newly deployed address
deployer.deploy(A).then(function() {
  return deployer.deploy(B, A.address);
});
```

Also not sure from your code what you're passing to the `TestICO` constructor in Solidity. It would make sense if it was an `address`. In your code I see the data type `ERC20` without any definition. 

Additionally - to debug this issue, you might consider writing some simple [JS tests](http://truffleframework.com/docs/getting_started/javascript-tests) for the deployment. They're easier to work with than the `migrations` and you'll end up with a clearer understanding of what's going on. The Zeppelin unit tests are an excellent resource for how to do this. You should be able to pass a simple test first:
```javascript
it('should deploy', async function(){
  const ico = await TestIco.new(); // <-- What should the constructor argument here be? 
})
```

**Comment by reasv** [comment]
Yeah, sorry that I didn't reply. I'm using tests now and it works.

**Comment by cgewecke** [comment]
Thanks @reasv!

**Comment by alsco77** [comment]
I am having this same issue @reasv , can you please help me by telling me what you done to resolve this? Even the approach you took with testing? I can't figure out how to get visibility on the error
